# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Color.create(:color => '#ffdead')
Color.create(:color => '#c0c0c0')
Color.create(:color => '#f0f8ff')
Color.create(:color => '#4169e1')
Color.create(:color => '#0000cd')
Color.create(:color => '#0000ff')
Color.create(:color => '#1e90ff')
Color.create(:color => '#6495ed')
Color.create(:color => '#00bfff')
Color.create(:color => '#87cefa')
Color.create(:color => '#87ceeb')
Color.create(:color => '#add8e6')
Color.create(:color => '#b0e0e6')
Color.create(:color => '#afeeee')
Color.create(:color => '#e0ffff')
Color.create(:color => '#00ffff')
Color.create(:color => '#40e0d0')
Color.create(:color => '#00ced1')
Color.create(:color => '#20b2aa')
Color.create(:color => '#008b8b')
Color.create(:color => '#008000')
Color.create(:color => '#228b22')
Color.create(:color => '#3cb371')
Color.create(:color => '#66cdaa')
Color.create(:color => '#7fffd4')
Color.create(:color => '#98fb98')
Color.create(:color => '#90ee90')
Color.create(:color => '#00ff7f')
Color.create(:color => '#7cfc00')
Color.create(:color => '#adff2f')
Color.create(:color => '#00ff00')
Color.create(:color => '#32cd32')
Color.create(:color => '#9acd32')
Color.create(:color => '#ffff00')
Color.create(:color => '#ffd700')
Color.create(:color => '#ffa500')
Color.create(:color => '#f4a460')
Color.create(:color => '#ff8c00')
Color.create(:color => '#daa520')
Color.create(:color => '#d2691e')
Color.create(:color => '#f08080')
Color.create(:color => '#fa8072')
Color.create(:color => '#ffa07a')
Color.create(:color => '#ff7f50')
Color.create(:color => '#ff6347')
Color.create(:color => '#ff4500')
Color.create(:color => '#ff0000')
Color.create(:color => '#c71585')
Color.create(:color => '#ff1493')
Color.create(:color => '#ff69b4')
Color.create(:color => '#ffc0cb')
Color.create(:color => '#ffb6c1')
Color.create(:color => '#ff00ff')
Color.create(:color => '#ee82ee')
Color.create(:color => '#da70d6')
Color.create(:color => '#ba55d3')
Color.create(:color => '#9370db')
Color.create(:color => '#7b68ee')

